version: "3"

services:
  openapi-nodejs:
    container_name: openapi-nodejs
    image: node:20.11.0-alpine3.19
    tty: true
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
